import App from "@/component/App";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Umphu App</title>
        <meta name="description" content="Generated by Umphu App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <App />
    </>
  );
}
